import { useEffect, useState, type FormEvent } from "react";
import { api } from "../api";
import { ErrorMessage, PageHeader } from "../components/Ui";
import type { Category } from "../types";
export function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ name: "", description: "" }); const [editing, setEditing] = useState<number | null>(null);
  const load = async () => { try { setCategories((await api.categories()).categories); } catch (e) { setError(e instanceof Error ? e.message : "Could not load categories."); } };
  useEffect(() => { void load(); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); try { if (editing) await api.updateCategory(editing, form); else await api.createCategory(form); setForm({ name: "", description: "" }); setEditing(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save category."); } }
  function startEdit(category: Category) { setEditing(category.id); setForm({ name: category.name, description: category.description }); }
  async function remove(category: Category) { if (!window.confirm(`Delete “${category.name}”? Categories used by tickets cannot be deleted.`)) return; try { await api.deleteCategory(category.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not delete category."); } }
  return <><PageHeader title="Categories" /><div className="admin-grid"><form className="form-card" onSubmit={submit}><h2>{editing ? "Edit category" : "New category"}</h2><ErrorMessage error={error} /><label>Name<input maxLength={100} required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Description<textarea maxLength={500} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><div className="form-actions"><button className="button button-primary compact">{editing ? "Save changes" : "Create category"}</button>{editing && <button type="button" className="button button-secondary compact" onClick={() => { setEditing(null); setForm({ name: "", description: "" }); }}>Cancel</button>}</div></form><section className="section-card"><h2>Existing categories</h2>{categories.length ? <div className="item-list">{categories.map(c => <article key={c.id}><div><strong>{c.name}</strong><p>{c.description || "No description"}</p></div><div className="actions"><button className="button button-secondary compact" onClick={() => startEdit(c)}>Edit</button><button className="button button-danger compact" onClick={() => void remove(c)}>Delete</button></div></article>)}</div> : <p className="muted">No categories available.</p>}</section></div></>;
}
